version: "3"

volumes:
  quiz_pg_db:

services:
  database:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=quiz_db
    volumes:
      - quiz_pg_db:/var/lib/postgresql/data

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: db-app
    ports:
      - 8000:5000
    environment:
      - DATABASE_URL=postgresql://docker:docker@database/quiz_db
    depends_on:
      - database