# Test few requests

###
POST http://localhost:5000/
Content-Type: application/json

{
  "questions_num": 5
}

###
POST http://localhost:5000/
Content-Type: application/json

{
  "questions_num": 0
}

###
POST http://0.0.0.0:8080
Content-Type: application/json

{
  "questions_num": 3
}